// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmrxdutskdpsqynmjnqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcnhkdXRza2Rwc3F5bm1qbnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzc4NTksImV4cCI6MjA3NDcxMzg1OX0.RP04gNC45tcJbteUbZgf84S52mAhLUt38cpQA1Ioiec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});